# Generated by Django 2.2.1 on 2019-06-11 08:48

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='article_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='analytic',
            name='article_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='analytic',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analytic',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analytic',
            name='short_description_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='analytic',
            name='short_description_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 11, 8, 48, 8, 934460)),
        ),
    ]
