# Generated by Django 2.2.1 on 2019-06-11 08:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0002_auto_20190611_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 11, 8, 52, 52, 457848)),
        ),
    ]
