# Generated by Django 2.2.1 on 2019-06-12 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20190612_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 14, 24, 22, 765968)),
        ),
    ]
