# Generated by Django 2.2.1 on 2019-06-11 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20190611_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 11, 8, 56, 41, 191921)),
        ),
    ]
