# Generated by Django 2.2.1 on 2019-06-12 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20190612_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 14, 28, 48, 861601)),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
