# Generated by Django 2.2.1 on 2019-06-13 09:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20190613_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytic',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='analytic',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='analytic',
            old_name='name_ru',
            new_name='title_ru',
        ),
        migrations.AlterField(
            model_name='analytic',
            name='article',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='article_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='article_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=5000, null=True),
        ),
    ]
