# Generated by Django 2.2.1 on 2019-06-14 10:06

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20190613_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytic',
            name='facebook_link',
        ),
        migrations.AddField(
            model_name='analytic',
            name='term',
            field=models.IntegerField(choices=[(1, 'Short'), (2, 'Long')], default=1),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='currency_pair_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='go_to_trade_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='is_published',
            field=models.BooleanField(db_column='foo', default=False),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('title',), unique=True, verbose_name='slug'),
        ),
    ]
