# Generated by Django 2.2.1 on 2019-06-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20190614_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytic',
            name='is_published',
        ),
    ]
