# Generated by Django 2.2.1 on 2019-06-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_remove_analytic_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytic',
            name='post_type',
        ),
    ]
