# Generated by Django 2.2.1 on 2019-06-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_remove_analytic_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
