# Generated by Django 2.2.1 on 2019-06-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_analytic_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='articles/img'),
        ),
        migrations.AddField(
            model_name='analytic',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='articles/img'),
        ),
        migrations.AddField(
            model_name='analytic',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='articles/img'),
        ),
        migrations.AddField(
            model_name='analytic',
            name='section',
            field=models.IntegerField(choices=[(1, 'Article')], default=1),
        ),
    ]
