# -*- coding: utf-8 -*-## Generated by Django 2.2.1 on 2019-07-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_auto_20190626_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytic',
            name='picture3',
        ),
    ]
