# Generated by Django 2.2.1 on 2019-06-04 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Company'), (2, 'Adviser')], default=1, help_text='Account type')),
                ('name', models.CharField(help_text='Company name or adviser first name', max_length=50)),
                ('name_en', models.CharField(help_text='Company name or adviser first name', max_length=50, null=True)),
                ('name_ru', models.CharField(help_text='Company name or adviser first name', max_length=50, null=True)),
                ('short_description', models.CharField(help_text='Short description displayed in sidebar', max_length=300)),
                ('short_description_en', models.CharField(help_text='Short description displayed in sidebar', max_length=300, null=True)),
                ('short_description_ru', models.CharField(help_text='Short description displayed in sidebar', max_length=300, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('member_since', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(default='images/default-ava.png', upload_to='images/advisers/')),
                ('surname', models.CharField(blank=True, help_text="Adviser's surname", max_length=255, null=True)),
                ('surname_en', models.CharField(blank=True, help_text="Adviser's surname", max_length=255, null=True)),
                ('surname_ru', models.CharField(blank=True, help_text="Adviser's surname", max_length=255, null=True)),
                ('long_description', models.CharField(blank=True, help_text="Company's benefits", max_length=700, null=True)),
                ('long_description_en', models.CharField(blank=True, help_text="Company's benefits", max_length=700, null=True)),
                ('long_description_ru', models.CharField(blank=True, help_text="Company's benefits", max_length=700, null=True)),
                ('trading_volume', models.CharField(blank=True, help_text='24h trading volume', max_length=255, null=True)),
                ('rating', models.CharField(blank=True, help_text='Rating CoinMarketCap', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'adviser',
                'verbose_name_plural': 'advisers',
            },
        ),
        migrations.CreateModel(
            name='GeneralFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_followers', models.CharField(max_length=100)),
                ('twitter_followers', models.CharField(max_length=100)),
                ('facebook_followers', models.CharField(max_length=100)),
                ('trading_volumes', models.CharField(max_length=100)),
                ('active_trades', models.CharField(max_length=100)),
                ('fiat_currencies', models.CharField(max_length=100)),
                ('trading_pairs', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'general fields',
                'verbose_name_plural': 'general fields',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('surname_en', models.CharField(max_length=100, null=True)),
                ('surname_ru', models.CharField(max_length=100, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('job_title_en', models.CharField(max_length=255, null=True)),
                ('job_title_ru', models.CharField(max_length=255, null=True)),
                ('telegram', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('avatar', models.ImageField(default='images/default-ava.png', upload_to='images')),
            ],
            options={
                'verbose_name': 'sale manager',
                'verbose_name_plural': 'sale managers',
            },
        ),
    ]
