# Generated by Django 2.2.1 on 2019-05-28 14:52
# -*- coding: utf-8 -*-
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Company'), (2, 'Adviser')], help_text='Account type')),
                ('name', models.CharField(help_text='Company name or adviser first name', max_length=50)),
                ('partner_type', models.CharField(help_text='Type of partner', max_length=255)),
                ('short_description', models.CharField(help_text='Short description displayed in sidebar', max_length=300)),
                ('telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('lang', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=3)),
                ('surname', models.CharField(blank=True, help_text="Adviser's surname", max_length=255, null=True)),
                ('long_description', models.CharField(blank=True, help_text="Company's benefits", max_length=700, null=True)),
                ('trading_volume', models.IntegerField(blank=True, help_text='24h trading volume', null=True)),
                ('rating', models.IntegerField(blank=True, help_text='Rating CoinMarketCap', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('telegram', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'sale manager',
                'verbose_name_plural': 'sale managers',
            },
        ),
    ]
