# Generated by Django 2.2.1 on 2019-05-28 14:56
# -*- coding: utf-8 -*-
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Adviser',
        ),
    ]
