# -*- coding: utf-8 -*-# Generated by Django 2.2.1 on 2019-06-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adviser',
            options={'verbose_name': 'Ambassador', 'verbose_name_plural': 'Ambassadors'},
        ),
        migrations.RemoveField(
            model_name='adviser',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='adviser',
            name='surname_en',
        ),
        migrations.RemoveField(
            model_name='adviser',
            name='surname_ru',
        ),
        migrations.AlterField(
            model_name='adviser',
            name='name',
            field=models.CharField(help_text='Company name or adviser first name', max_length=250),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='name_en',
            field=models.CharField(help_text='Company name or adviser first name', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='name_ru',
            field=models.CharField(help_text='Company name or adviser first name', max_length=250, null=True),
        ),
    ]
