# Generated by Django 2.2.1 on 2019-05-28 15:06
# -*- coding: utf-8 -*-
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0002_auto_20190528_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='avatar',
            field=models.ImageField(default=None, upload_to='app/img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adviser',
            name='member_since',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
