# Generated by Django 2.2.1 on 2019-06-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0002_auto_20190607_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='name',
            field=models.CharField(help_text='Company name or adviser first name', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='name_en',
            field=models.CharField(help_text='Company name or adviser first name', max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='name_ru',
            field=models.CharField(help_text='Company name or adviser first name', max_length=250, null=True, unique=True),
        ),
    ]
