# Generated by Django 2.2.1 on 2019-05-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0004_auto_20190528_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='avatar',
            field=models.ImageField(default='static/images/default-avatar.png', upload_to='img/contacts/'),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='avatar',
            field=models.ImageField(default='static/images/default-avatar.png', upload_to='img/advisers/'),
        ),
    ]
