# Generated by Django 2.2.1 on 2019-05-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0005_auto_20190528_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviser',
            name='lang',
        ),
        migrations.AddField(
            model_name='adviser',
            name='long_description_en',
            field=models.CharField(blank=True, help_text="Company's benefits", max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='long_description_ru',
            field=models.CharField(blank=True, help_text="Company's benefits", max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='name_en',
            field=models.CharField(help_text='Company name or adviser first name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='name_ru',
            field=models.CharField(help_text='Company name or adviser first name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='partner_type_en',
            field=models.CharField(help_text='Type of partner', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='partner_type_ru',
            field=models.CharField(help_text='Type of partner', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='short_description_en',
            field=models.CharField(help_text='Short description displayed in sidebar', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='short_description_ru',
            field=models.CharField(help_text='Short description displayed in sidebar', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='surname_en',
            field=models.CharField(blank=True, help_text="Adviser's surname", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='surname_ru',
            field=models.CharField(blank=True, help_text="Adviser's surname", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='job_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='job_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='surname_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='surname_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
