# Generated by Django 2.2.1 on 2019-06-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0005_auto_20190610_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='ambassador_type_en',
            field=models.CharField(blank=True, default='Verified Ambassador', help_text='Type of ambassador/sales/company', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='ambassador_type_ru',
            field=models.CharField(blank=True, default='Verified Ambassador', help_text='Type of ambassador/sales/company', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='page_title_en',
            field=models.CharField(blank=True, default='Ambassador Exrates Exchange', help_text='Title of the page', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='page_title_ru',
            field=models.CharField(blank=True, default='Ambassador Exrates Exchange', help_text='Title of the page', max_length=255, null=True),
        ),
    ]
