# Generated by Django 2.2.1 on 2019-05-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0006_auto_20190528_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='member_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='partner_type',
            field=models.CharField(blank=True, help_text='Type of partner', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='partner_type_en',
            field=models.CharField(blank=True, help_text='Type of partner', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='partner_type_ru',
            field=models.CharField(blank=True, help_text='Type of partner', max_length=255, null=True),
        ),
    ]
