# -*- coding: utf-8 -*-# Generated by Django 2.2.1 on 2019-06-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0007_auto_20190614_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='deal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
