# -*- coding: utf-8 -*-# Generated by Django 2.2.1 on 2019-06-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0008_adviser_deal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviserPipeDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adviser_id', models.CharField(max_length=36)),
                ('deal_id', models.IntegerField()),
                ('workspace', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='adviser',
            name='deal_id',
        ),
    ]
