# Generated by Django 2.2.1 on 2019-05-31 16:01
# -*- coding: utf-8 -*-
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0008_auto_20190530_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='avatar',
            field=models.ImageField(default='images/default-ava.png', upload_to='images'),
        ),
    ]
