# Generated by Django 2.2.1 on 2019-05-31 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0009_auto_20190531_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviser',
            name='partner_type',
        ),
        migrations.RemoveField(
            model_name='adviser',
            name='partner_type_en',
        ),
        migrations.RemoveField(
            model_name='adviser',
            name='partner_type_ru',
        ),
    ]
