# -*- coding: utf-8 -*-# Generated by Django 2.2.1 on 2019-06-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0010_deal_dealpipedrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealpipedrive',
            name='deal_model_id',
            field=models.IntegerField(),
        ),
    ]
