# Generated by Django 2.2.1 on 2019-06-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0010_auto_20190531_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_followers', models.CharField(max_length=100)),
                ('twitter_followers', models.CharField(max_length=100)),
                ('facebook_followers', models.CharField(max_length=100)),
                ('trading_volumes', models.CharField(max_length=100)),
                ('active_trades', models.CharField(max_length=100)),
                ('fiat_currencies', models.CharField(max_length=100)),
                ('trading_pairs', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'general fields',
                'verbose_name_plural': 'general fields',
            },
        ),
        migrations.AlterField(
            model_name='adviser',
            name='avatar',
            field=models.ImageField(default='images/default-ava.png', upload_to='images/advisers/'),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='rating',
            field=models.CharField(blank=True, help_text='Rating CoinMarketCap', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='trading_volume',
            field=models.CharField(blank=True, help_text='24h trading volume', max_length=255, null=True),
        ),
    ]
