# Generated by Django 2.2.1 on 2019-07-15 16:00
# -*- coding: utf-8 -*-#
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0011_auto_20190623_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='avatar',
            field=models.ImageField(default='img/pics/default-avatar.svg', upload_to='images/advisers/'),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='type',
            field=models.IntegerField(choices=[(1, 'Company'), (2, 'Ambassador'), (3, 'Sales'), (4, 'Advisor')], default=1, help_text='Account type'),
        ),
    ]
