X XXXX
    XXXX XXXXXXXXXXX

X XXXXXXXXXXXX
    XXX XXXXXXX

X XXXX
	XXXXXXXXX XXXXXXX
	XXXXXXXX XXXXX
	XXXXXXXXXX XXXXXX XXXX
	XXXXXXXXXXX XXXXX XXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXX
	XXXX XXXXXXX XXXXX XXX
    XXXXXXXXX XXXXX XXXX XXXXXXXXXX XXXXXXXXXXX
